apiVersion: apps/v1
kind: Deployment
metadata:
 name: deploymentapp
 labels:
  app: myappv1
spec:
 replicas: 3
 selector:
  matchLabels: 
   app: payapp
 template:
  metadata:
   labels:
    app: payapp
  spec:
   containers:
    - name: nginx
      image: nginx:latest
      imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: searchapp
 labels:
  app: myappv2
spec:
 replicas: 3
 selector:
  matchLabels:
   app: seapp
 template:
  metadata:
   labels:
    app: seapp
  spec:
   containers:
    - name: nginx
      image: nginx:latest
      imagePullPolicy: IfNotPresent
