apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginxdeployment
  name: nginxdeployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginxdeployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginxdeployment
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        imagePullPolicy: IfNotPresent
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginxdeployment
  name: nginxdeployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginxdeployment
  type: ClusterIP
status:
  loadBalancer: {}
