apiVersion: v1
data:
  default.conf: |
    server {
     root /usr/share/nginx/html;
     server_name www.mojtaba.com;
     index index.html index.htm;
    }
kind: ConfigMap
metadata:
  name: nginxconfig
