apiVersion: v1
kind: Pod
metadata:
 name: pingserver
 labels:
  app: mypingserver
spec:
 containers:
  - name: myapp1
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
     - containerPort: 80
  - name: myapp2
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['ping', 'myapp1']
