apiVersion: v1
kind: Pod
metadata:
 name: webserve1
 labels:
  app: myapp1
spec:
 containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
     - containerPort: 80
