version: "3.8"
services:
 datapuller:
  container_name: datapuller
  build: ./build
  image: datapuller:v1
  volumes:
   - nginx_content_vol:/result
  restart:  always
 web:
  image: nginx:latest
  restart:  always
  ports:
   - 80:80
  volumes: 
   - nginx_content_vol:/usr/share/nginx/html
   - nginx_conf_vol:/etc/nginx/conf.d/
volumes:
 nginx_content_vol:
  external: true
 nginx_conf_vol:
  external: true
 
